### ISSUE TITLE
Install on Minikube fails

### ISSUE THREAD

**Issue by sebastiangaiser** [tektoncd/operator#899]
# Expected Behavior

```
minikube start
git clone https://github.com/tektoncd/operator.git
git checkout release-v0.60.x
helm upgrade --install -n tekton-operator --create-namespace --set installCRDs=true ./operator/chart
```

Operator is running...

# Actual Behavior
```
panic: open /var/run/ko/tekton-pipeline: permission denied

goroutine 1 [running]:
github.com/tektoncd/operator/pkg/reconciler/common.latestRelease(...)
	github.com/tektoncd/operator/pkg/reconciler/common/releases.go:174
github.com/tektoncd/operator/pkg/reconciler/common.TargetVersion({0x1d9e6b0, 0x0})
	github.com/tektoncd/operator/pkg/reconciler/common/releases.go:46 +0x5e
github.com/tektoncd/operator/pkg/reconciler/common.TargetManifest({0x1d9e6b0, 0x0})
	github.com/tektoncd/operator/pkg/reconciler/common/releases.go:51 +0x5f
github.com/tektoncd/operator/pkg/reconciler/common.AppendTarget({0x1ae623d, 0xc000024f90}, 0xc00082c280, {0x1d9e6b0, 0x0})
	github.com/tektoncd/operator/pkg/reconciler/common/stages.go:51 +0x4c
github.com/tektoncd/operator/pkg/reconciler/common.Controller.fetchSourceManifests({0xc00082c280, 0xc0000d6590, {0x1ae623d, 0x2}}, {0x1d459d8, 0xc0004bc300}, {0xff})
	github.com/tektoncd/operator/pkg/reconciler/common/initcontroller.go:95 +0x85
github.com/tektoncd/operator/pkg/reconciler/common.Controller.InitController({0x0, 0xc0000d6590, {0x1ae623d, 0x600000000000000}}, {0x1d459d8, 0xc0004bc300}, {0x40})
	github.com/tektoncd/operator/pkg/reconciler/common/initcontroller.go:70 +0x60c
github.com/tektoncd/operator/pkg/reconciler/kubernetes/tektonpipeline.NewExtendedController.func1({0x1d459d8, 0xc0004bc300}, {0x1ae3301, 0xc00017a0a0})
	github.com/tektoncd/operator/pkg/reconciler/kubernetes/tektonpipeline/controller.go:54 +0x9a
github.com/tektoncd/operator/pkg/reconciler/kubernetes/tektonpipeline.NewController({0x1d459d8, 0xc0004bc300}, {0x1d32e50, 0xc0003ce8a0})
	github.com/tektoncd/operator/pkg/reconciler/kubernetes/tektonpipeline/controller.go:41 +0x53
knative.dev/pkg/injection/sharedmain.ControllersAndWebhooksFromCtors({0x1d459d8, 0xc0004bc300}, 0x1, {0xc00079ff30, 0x8, 0x77359400})
	knative.dev/pkg@v0.0.0-20211206113427-18589ac7627e/injection/sharedmain/main.go:390 +0x15c
knative.dev/pkg/injection/sharedmain.MainWithConfig({0x1d46340, 0xc00000f780}, {0x1ae7b6d, 0xf}, 0xc000193d40, {0xc0006bff30, 0x8, 0x8})
	knative.dev/pkg@v0.0.0-20211206113427-18589ac7627e/injection/sharedmain/main.go:232 +0x5da
knative.dev/pkg/injection/sharedmain.MainWithContext({0x1d46340, 0xc00000f780}, {0x1ae7b6d, 0xf}, {0xc00055ff30, 0x8, 0x8})
	knative.dev/pkg@v0.0.0-20211206113427-18589ac7627e/injection/sharedmain/main.go:171 +0xe7
knative.dev/pkg/injection/sharedmain.Main({0x1ae7b6d, 0xf}, {0xc00055ff30, 0x8, 0x8})
	knative.dev/pkg@v0.0.0-20211206113427-18589ac7627e/injection/sharedmain/main.go:108 +0x8f
main.main()
	github.com/tektoncd/operator/cmd/kubernetes/operator/main.go:32 +0xb5
```

# Steps to Reproduce the Problem

See # Expected Behavior

# Additional Info

- Kubernetes version:

```
Client Version: v1.24.2
Server Version: v1.23.3
```

**Comment by sebastiangaiser** [comment]
Problem with my cluster...
